spring:
  application:
    name: backend

  datasource:
    url: ${dbProdUrl}
    username: ${dbProdUsername}
    password: ${dbProdPassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB





  digitalocean:
    secretKey: ${secretKey}
    accessKey: ${accessKey}
    region: ${region}
    bucketName: ${bucketName}